/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Property, Agent, Currency, DevelopmentProject } from './types';

export const EXCHANGE_RATES: Record<Currency, number> = {
  BDT: 1,
  USD: 0.0084, // Approximate rate BDT equivalent conversion metrics
  EUR: 0.0078,
};

export const CURRENCY_SYMBOLS: Record<Currency, string> = {
  BDT: '৳',
  USD: '$',
  EUR: '€',
};

export const PROPERTIES: Property[] = [
  {
    id: 'prop-bayside',
    title: 'AHS Jolshiri Signature Villa',
    location: 'Sector 16, Jolshiri Abashon, Dhaka',
    coast: 'North',
    priceBDT: 65000000,
    type: 'Villa',
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 280,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    description: 'A masterpiece of modern smart-city architecture, this signature residence captures open parkland views, premium marble finishes, and outstanding safety features in Sector 16.',
    features: ['Lake Access', 'Infinity Pool', 'Terrace Garden', '24/7 Gated Security'],
    isFeatured: true,
  },
  {
    id: 'prop-1',
    title: 'The Solaris Prime Estate',
    location: 'Sector 16, Jolshiri Abashon, Dhaka',
    coast: 'North',
    priceBDT: 125000000,
    type: 'Villa',
    bedrooms: 5,
    bathrooms: 5.5,
    areaSqm: 520,
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    description: 'This masterfully designed residential estate features double-height glass panels opening onto a lush green lawn, completely capturing the essence of modern Jolshiri elite living.',
    features: ['Infinity Pool', 'Security Enclave', 'Automated Smart Systems', 'Chef Kitchen', 'Bespoke Fittings'],
    isFeatured: true,
  },
  {
    id: 'prop-2',
    title: 'The Cantonment Heights Penthouse',
    location: 'Rajnigandha Tower Area, Dhaka Cantonment',
    coast: 'South',
    priceBDT: 85000000,
    type: 'Penthouse',
    bedrooms: 3,
    bathrooms: 3.5,
    areaSqm: 310,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    description: 'Boasting uninterrupted panoramic views of the military enclave, this premium penthouse features double-height ceilings, a wrap-around sky terrace, and private card-access elevators.',
    features: ['Cantonment Views', 'Sky Terrace', 'Private Jacuzzi', '24/7 Military-Grade Security', 'Gym Access'],
    isFeatured: true,
  },
  {
    id: 'prop-3',
    title: 'Jolshiri Serene Apartments',
    location: 'Sector 15, Jolshiri Abashon, Dhaka',
    coast: 'East',
    priceBDT: 42000000,
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 145,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    description: 'Experience pure urban serenity in this modern canal-facing apartment. Walk directly onto the landscaped greenways of Jolshiri and enjoy refreshing tree-lined views.',
    features: ['Canal Facing', 'Manicured Gardens', 'Common Lounge & Pool', 'Fully Furnished', '24/7 Power Backup'],
    isFeatured: false,
  },
  {
    id: 'prop-4',
    title: 'Rajnigandha Luxury Duplex',
    location: 'Dhaka Cantonment, Dhaka',
    coast: 'South',
    priceBDT: 58000000,
    type: 'Duplex',
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 260,
    image: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1200&q=80',
    description: 'A stylish and spacious duplex positioned perfectly to capture secure cantonment living. Enjoy wide balconies, personal manicured lawns, and robust building structural safety.',
    features: ['Scenic City Views', 'Private Garden', 'Swimming Lounge', 'Walking Track Proximity', 'Solar Backup Panels'],
    isFeatured: false,
  },
  {
    id: 'prop-5',
    title: 'Nayapaltan Executive Residence',
    location: 'VIP Road, Nayapaltan, Dhaka',
    coast: 'West',
    priceBDT: 145000000,
    type: 'Villa',
    bedrooms: 6,
    bathrooms: 7,
    areaSqm: 680,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    description: 'Uncompromising prestige nestled on a secured plot along VIP Road. Features high-end security command, professional-grade home theater capabilities, and private corporate-meeting lounge.',
    features: ['City Skyline Views', 'Professional Boardroom', 'Private Cinema Loft', 'Double Garage', 'Guest Suite Pavilion'],
    isFeatured: true,
  },
  {
    id: 'prop-6',
    title: 'Jolshiri Lakeside Sanctuary',
    location: 'Sector 16, Jolshiri Abashon, Dhaka',
    coast: 'North',
    priceBDT: 36000000,
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 180,
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    description: 'Positioned in Jolshiri\'s most prestigious residential pocket. Offering premium imported fittings, an open-concept modular kitchen layout, and views overlooking the neighborhood lake.',
    features: ['Lakeside Balcony', 'Gated Community Access', 'Suburban Vistas', 'Underground Secure Parking', 'Storage Area'],
    isFeatured: false,
  },
];

export const AGENTS: Agent[] = [
  {
    name: 'Yalda Sheri',
    role: 'Senior Luxury Consultant',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    phone: '01625-555700',
    email: 'ahspropertiesdevelopmentltd@gmail.com',
    specialty: 'Exclusive Estates & Investment Portfolios',
  },
  {
    name: 'Junaid Nuzeebun',
    role: 'Founder & Principal Broker',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    phone: '01725-555700',
    email: 'ahspropertiesdevelopmentltd@gmail.com',
    specialty: 'Off-Market & High-Net-Worth Advisory',
  },
];

export const TRANSLATIONS = {
  EN: {
    heroTitle: "We Build Tomorrow's Addresses Today",
    heroSubtitle: 'Welcome to AHS Properties & Development Ltd. — premium real estate in beautiful Bangladesh. Experience pristine architectural design, secure sanctuaries, and elite properties designed for legacy living.',
    searchPlaceholder: 'Search by location, sector, or property...',
    allCoasts: 'All Locations',
    northCoast: 'Jolshiri Sector 16',
    eastCoast: 'Jolshiri Sector 15',
    southCoast: 'Dhaka Cantonment',
    westCoast: 'VIP Road / Nayapaltan',
    allTypes: 'All Property Types',
    villa: 'Villas',
    apartment: 'Apartments',
    penthouse: 'Penthouses',
    duplex: 'Duplexes',
    searchButton: 'Find Properties',
    featuredTitle: 'Signature Properties',
    featuredBtn: 'View All Properties',
    aboutTitle: 'What We Offer',
    aboutSubtitle: 'AHS represents the pinnacle of boutique real estate design and development in Bangladesh. Our premium services ensure precision at every stage of your real estate journey.',
    contactUs: 'Ready to Find Your Dream Property?',
    contactUsSub: 'Whether acquiring a primary home, a vacation sanctuary, or an investment asset, AHS is your trusted partner.',
    getStarted: 'Get Started',
    newsTitle: 'Real Estate & Investment Insights',
    newsSubtitle: 'Keep up with market trends, structural codes, and luxurious lifestyle offerings in Bangladesh.',
  },
  FR: {
    heroTitle: "Nous construisons aujourd'hui les adresses de demain",
    heroSubtitle: 'Bienvenue chez AHS Properties & Development Ltd. — immobilier d\'exception au Bangladesh. Découvrez des conceptions épurées, des sanctuaires urbains et des résidences durables.',
    searchPlaceholder: 'Rechercher par lieu, secteur ou propriété...',
    allCoasts: 'Toutes les zones',
    northCoast: 'Jolshiri Secteur 16',
    eastCoast: 'Jolshiri Secteur 15',
    southCoast: 'Cantonment de Dhaka',
    westCoast: 'VIP Road / Nayapaltan',
    allTypes: 'Tous types de propriétés',
    villa: 'Villas',
    apartment: 'Appartements',
    penthouse: 'Penthouses',
    duplex: 'Duplex',
    searchButton: 'Trouver',
    featuredTitle: 'Propriétés Signatures',
    featuredBtn: 'Toutes les Propriétés',
    aboutTitle: 'Ce Que Nous Offrons',
    aboutSubtitle: 'AHS représente le summum du développement et design immobilier de niche au Bangladesh. Nos services garantissent l\'excellence.',
    contactUs: 'Prêt à trouver votre propriété idéale ?',
    contactUsSub: 'AHS est votre partenaire de confiance absolue pour concrétiser vos projets de vie au Bangladesh.',
    getStarted: 'Commencer',
    newsTitle: 'Marché Immobilier & Tendances',
    newsSubtitle: 'Suivez les tendances du marché, les codes de construction et le mode de vie haut de gamme au Bangladesh.',
  }
};

export const DEVELOPMENT_PROJECTS: DevelopmentProject[] = [
  {
    id: 'proj-147-intl2',
    title: 'AHS Jolshiri Central 16',
    location: 'Sector 16, Jolshiri Abashon, Dhaka',
    coast: 'North',
    startingPriceBDT: 23000000,
    type: 'Apartments',
    availableUnits: 4,
    totalUnits: 7,
    percentAvailable: 57,
    status: 'UNDER CONSTRUCTION',
    description: "Located in the premium core of Sector 16, AHS Jolshiri Central offers an exclusive lifestyle in the nation's premier smart city. Experience modern architectural beauty, smart systems integration, and open scenic vistas.",
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-west-bay',
    title: 'AHS VIP Square',
    location: 'VIP Road, Nayapaltan, Dhaka',
    coast: 'West',
    startingPriceBDT: 24000000,
    type: 'Apartments',
    availableUnits: 2,
    totalUnits: 11,
    percentAvailable: 18,
    status: 'UNDER CONSTRUCTION',
    description: "Ideally located in Nayapaltan, VIP Square offers high-connectivity workspaces and executive residences. Merging urban convenience with high structural safety parameters.",
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-river-edge',
    title: 'AHS Jolshiri Lakeview 15',
    location: 'Sector 15, Jolshiri Abashon, Dhaka',
    coast: 'East',
    startingPriceBDT: 15000000,
    type: 'Apartments',
    availableUnits: 5,
    totalUnits: 5,
    percentAvailable: 100,
    status: 'PRE LAUNCH MARKETING',
    description: "AHS Jolshiri Lakeview 15 is a refined collection of residences positioned next to the beautiful central canals of Jolshiri Abashon. Merging quiet green sanctuaries with great roads connectivity.",
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-coastal-view-3',
    title: 'AHS Cantonment Crest',
    location: 'Dhaka Cantonment, Dhaka',
    coast: 'South',
    startingPriceBDT: 13000000,
    type: 'Apartments',
    availableUnits: 8,
    totalUnits: 16,
    percentAvailable: 50,
    status: 'UNDER CONSTRUCTION',
    description: "AHS Cantonment Crest is an elite contemporary development positioned inside the highly secure Cantonment zone. Perfect for families seeking a peaceful retreat backed by military-standard utilities and security.",
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-emara',
    title: 'AHS Jolshiri Boulevard',
    location: 'Sector 16, Jolshiri Abashon, Dhaka',
    coast: 'North',
    startingPriceBDT: 25000000,
    type: 'Apartments',
    availableUnits: 2,
    totalUnits: 6,
    percentAvailable: 33,
    status: 'UNDER CONSTRUCTION',
    description: "AHS Jolshiri Boulevard is a premium boutique development ideally positioned along the prime avenue of Sector 16. Crafted with finest imported materials and excellent ventilation layouts.",
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-amali',
    title: 'AHS Jolshiri Green Gardens',
    location: 'Sector 16, Jolshiri Abashon, Dhaka',
    coast: 'North',
    startingPriceBDT: 19500000,
    type: 'Apartments',
    availableUnits: 15,
    totalUnits: 17,
    percentAvailable: 88,
    status: 'PRE LAUNCH MARKETING',
    description: "AHS Green Gardens is a premium smart residence development in Sector 16, Jolshiri. Designed for sustainable living, containing beautiful walking tracks and advanced fire safety systems.",
    image: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-le-loft',
    title: 'AHS Nayapaltan Heights',
    location: 'VIP Road, Nayapaltan, Dhaka',
    coast: 'West',
    startingPriceBDT: 8500000,
    type: 'Apartments',
    availableUnits: 3,
    totalUnits: 8,
    percentAvailable: 38,
    status: 'PRE LAUNCH MARKETING',
    description: "Located in the heart of Nayapaltan, this high-rise residence offers supreme access to offices, shopping complexes, and everyday amenities with full security control systems.",
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80'
  },
  {
    id: 'proj-vantage',
    title: 'AHS Cantonment View',
    location: 'Rajnigandha Tower Area, Dhaka Cantonment',
    coast: 'South',
    startingPriceBDT: 9500000,
    type: 'Apartments',
    availableUnits: 11,
    totalUnits: 25,
    percentAvailable: 44,
    status: 'UNDER CONSTRUCTION',
    description: "A high-end estate next to Cantonment gates, Cantonment View offers complete peace of mind, high administrative safety, and unbeatable access to prime urban regions.",
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
  }
];
